# Artificial Neural Network
## Multi Classification

In [79]:
#importing dependencies
import pandas as pd 
import numpy as np
from sklearn.datasets import load_iris

In [80]:
#loading dataset into dataframe
df = load_iris()

In [81]:
#spliting data 
x = df.data
y = df.target

In [76]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [82]:
#encoding label
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y1 = label.fit_transform(y)
y = pd.get_dummies(y1).values

In [83]:
#spliting data into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [86]:
#scaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [87]:
print(x_train.shape)
print(y_train.shape)

(120, 4)
(120, 3)


In [88]:
#import model platform 
import keras
from keras.models import sequential
from keras.layers import Dense

In [89]:
from keras.engine.sequential import Sequential
#training model
classifier = Sequential()

#adding first hidden layer and input
classifier.add(Dense(4,input_shape=(4,),activation='relu'))

#adding the output layer
classifier.add(Dense(3,activation='softmax'))

In [90]:
classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [91]:
print(x_train.shape)
print(y_train.shape)

(120, 4)
(120, 3)


In [ ]:
classifier.fit(x=x_train,y=y_train,batch_size=10,epochs=10)

In [99]:
#prediction 
y_pred = classifier.predict(x_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [100]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        13
           1       0.64      0.78      0.70         9
           2       0.57      0.50      0.53         8

    accuracy                           0.77        30
   macro avg       0.74      0.73      0.73        30
weighted avg       0.78      0.77      0.77        30

[[12  0  1]
 [ 0  7  2]
 [ 0  4  4]]


In [102]:
(12+7+4)/30

0.7666666666666667