# Artificial Neural Network
## Multi Classification

In [23]:
#importing dependencies
import pandas as pd 
import numpy as np
from sklearn.datasets import load_iris

In [24]:
#loading dataset into dataframe
df = load_iris()

In [25]:
#spliting data 
x = df.data
y = df.target

In [26]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [45]:
#encoding label
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y1 = label.fit_transform(y)
y = pd.get_dummies(y1).values

In [46]:
#spliting data into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [47]:
#scaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [48]:
print(x_train.shape)
print(y_train.shape)

(120, 4)
(120, 3)


In [49]:
#import model platform 
import keras
from keras.models import sequential
from keras.layers import Dense
from keras.layers import Flatten

In [50]:
from keras.engine.sequential import Sequential
#training model
classifier = Sequential()
#input layer
classifier.add(Flatten(input_shape=(4,)))
#adding first hidden layer and input
classifier.add(Dense(4,activation='relu'))

#adding the output layer
classifier.add(Dense(3,activation='softmax'))

In [54]:
classifier.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [52]:
print(x_train.shape)
print(y_train.shape)

(120, 4)
(120, 3)


In [55]:
classifier.fit(x=x_train,y=y_train,batch_size=10,epochs=10)

Epoch 1/10
12/12 [==============================] - 0s 2ms/step - loss: 1.5069 - accuracy: 0.4750
Epoch 2/10
12/12 [==============================] - 0s 2ms/step - loss: 1.4450 - accuracy: 0.3500
Epoch 3/10
12/12 [==============================] - 0s 2ms/step - loss: 1.3832 - accuracy: 0.3417
Epoch 4/10
12/12 [==============================] - 0s 2ms/step - loss: 1.3362 - accuracy: 0.3250
Epoch 5/10
12/12 [==============================] - 0s 2ms/step - loss: 1.2929 - accuracy: 0.3167
Epoch 6/10
12/12 [==============================] - 0s 2ms/step - loss: 1.2541 - accuracy: 0.3333
Epoch 7/10
12/12 [==============================] - 0s 2ms/step - loss: 1.2217 - accuracy: 0.3250
Epoch 8/10
12/12 [==============================] - 0s 2ms/step - loss: 1.1911 - accuracy: 0.3250
Epoch 9/10
12/12 [==============================] - 0s 2ms/step - loss: 1.1633 - accuracy: 0.3167
Epoch 10/10
12/12 [==============================] - 0s 2ms/step - loss: 1.1357 - accuracy: 0.3167


In [58]:
y_pred = classifier.predict(x_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [60]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.18      0.60      0.27         5
           2       0.75      0.38      0.50        16

    accuracy                           0.30        30
   macro avg       0.31      0.33      0.26        30
weighted avg       0.43      0.30      0.31        30

[[0 9 0]
 [0 3 2]
 [5 5 6]]


### Tradeoff and incredible error

In [61]:
# importing libraries
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

In [64]:
# defining function
def built_classifier():
  classifier = Sequential()
  classifier.add(Dense(16,activation='relu',input_shape=(4,)))
  classifier.add(Dense(16,activation='relu'))
  classifier.add(Dense(1,activation='linear'))
  classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
  return classifier

In [65]:
classifier = KerasClassifier(build_fn=built_classifier,batch_size=100,epochs=10)
accuracy = cross_val_score(estimator=classifier,X=x_train,y=y_train,cv=10,n_jobs=-1)
accuracy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead.
  """Entry point for launching an IPython kernel.


array([0.66666669, 0.6388889 , 0.6388889 , 0.66666669, 0.66666669,
       0.66666669, 0.66666669, 0.6388889 , 0.6388889 , 0.66666669])

In [66]:
accuracy.mean()

0.6555555701255799

In [67]:
accuracy.std()

0.013608282837727255